### ISSUE TITLE
Add support for pytwin import by multiple python processes

### ISSUE THREAD

**Issue by lboucin** [ansys/pytwin#102]
### 📝 Description of the feature

**PyTwin does not support import by multiple python processes**.

This is due to the way the logging and working directory are setup by `pytwin.settings` when importing pytwin in a given python processes.

The feature will be to let user `import pytwin` in multiple python processes running at the same time and call any public method from the `pytwin.settings` module in such context.

### 💡 Steps for implementing the feature

One possible quick solution would be to add the python process id in the working directory path (see `pytwin.settings.PYTWIN_SETTINGS.working_dir` and how `pytwin.evaluate.model.model_dir` is working with it).

One difficulty is to handle the working directory migration when `pytwin.settings.modify_pytwin_working_dir` is called.

This should be refined based on the contexts where this issue has been encountered:

### - SAF context
_To be described (@ansJBoly could you please do so? Thanks!)_
### - Digital Twin context
_To be described (@EDCarman could you please do so? Thanks!)_

**Comment by ansJBoly** [comment]
**SAF context**

1. _What is SAF ?_
SAF, Solution Applications Framework, is a development framework delivered by the `Ansys® Solution Applications <https://github.com/Solution-Applications>`_
3. _How to create a SAF solution ?_

**Comment by EDCarman** [comment]
@lboucin , the specific context where I encountered this for digital twin was during app development and testing.

Here, I have an interactive Python session, with PyTwin imported, running in the IDE for testing command snippets. If I then want to run the full code e.g. for debugging, it will fail on PyTwin import due to directory clash. In this case, the workaround would be to change the working dir in the interactive session.
A second example would be while the debugging session is running and paused, I might want to run another script or launch an interactive window. Again PyTwin import fails due to directory clash. Here, it may not be desirable, or possible, to change the working directory mid-debugging session, so the only way to proceed would be to stop the debugging session.
In this use case, multiple Python sessions will be launched and closed, so if there is not a way to remove temporary folders, they would very quickly accumulate.

A second case that I could see would be for deployment workflows where you may have one twin running continuously and you need to launch separate models for what-if testing or forecasting. Though this may, perhaps, be better covered by containerisation. @chrpetre any thoughts here?
